name: Minecraft Robot Plugin
version: 1.0
main: com.example.robotplugin.RobotPlugin
commands:
  avance:
    description: Move the robot forward
    usage: /<command> <distance>
  recule:
    description: Move the robot backward
    usage: /<command> <distance>